### ISSUE TITLE
error in running class BaseEnv(ABC, gym.Env)? how can i fix it?

### ISSUE THREAD

**Issue by Schopenhauer-loves-Hegel** [opendilab/ACE#4]
/home/tj/.conda/envs/ace/lib/python3.8/site-packages/namedlist.py:252: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  if isinstance(field_names, _collections.Mapping):
Traceback (most recent call last):
  File "exp/smac/corridor/config.py", line 4, in <module>
    from ding.entry import serial_pipeline
  File "/home/tj/ACE/ding/entry/__init__.py", line 2, in <module>
    from .serial_entry import serial_pipeline
  File "/home/tj/ACE/ding/entry/serial_entry.py", line 8, in <module>
    from ding.envs import get_vec_env_setting, create_env_manager
  File "/home/tj/ACE/ding/envs/__init__.py", line 1, in <module>
    from .env import *
  File "/home/tj/ACE/ding/envs/env/__init__.py", line 1, in <module>
    from .base_env import BaseEnv, get_vec_env_setting, BaseEnvTimestep, BaseEnvInfo, get_env_cls
  File "/home/tj/ACE/ding/envs/env/base_env.py", line 14, in <module>
    class BaseEnv(ABC, gym.Env):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

**Comment by yifan123** [comment]
It seems to be an issue with the gym version. Please refer to the following link: https://github.com/sail-sg/envpool/issues/166. You can fix it by `pip install gym<0.25`
